/*
 * OpenAPI Learning
 *
 * OpenAPI for Learning
 *
 * API version: 1
 * Contact: alfaeliaswaristino@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Success bool `json:"success,omitempty"`
}
