/*
 * OpenAPI Learning
 *
 * OpenAPI for Learning
 *
 * API version: 1
 * Contact: alfaeliaswaristino@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Todolist struct {
	// todolistId
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Priority float64 `json:"priority,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
